name: portfolio
description: "My Portfolio App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.0.0
  url_strategy: ^0.3.0
  material_color_utilities: ^0.11.1
  logger: ^2.0.2+1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  graphql_flutter: ^5.2.0-beta.8
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/



